version: '3.8'
services:
  frontend:
    build:
        context: ./frontend
        dockerfile: ./Dockerfile
    command: npm start
    volumes:
      - .:/lab-app/frontend
    ports:
      - "3000:3000"